weather_mappings={
   'Clear': 0,
    'Partly Cloudy': 1,
    'Scattered Clouds': 1,
    'Mostly Cloudy': 2,
    'Patches of Fog': 2,
    'Shallow Fog': 2,
    'Haze': 3,
    'Light Drizzle': 3,
    'Drizzle': 4,
    'Mist': 4,
    'Fog': 4,
    'Smoke': 5,
    'Light Haze': 5,
    'Thunderstorm': 6,
    'Thunderstorms and Rain': 7,
    'Light Thunderstorm': 6,
    'Light Thunderstorms and Rain': 7,
    'Heavy Thunderstorms and Rain': 8,
    'Heavy Thunderstorms with Hail': 9,
    'Thunderstorms with Hail': 8,
    'Rain': 6,
    'Light Rain': 6,
    'Light Rain Showers': 6,
    'Overcast': 5,
    'Heavy Rain': 7,
    'Funnel Cloud': 8,
    'Widespread Dust': 4,
    'Squalls': 8,
    'Unknown': 0,
}

direction_mapping={
   'North': 1,
    'West': 4,
    'WNW': 4,
    'East': 3,
    'NW': 1,
    'WSW': 4,
    'ESE': 3,
    'ENE': 3,
    'SE': 3,
    'SW': 2,
    'NNW': 1,
    'NE': 3,
    'SSE': 2,
    'SSW': 2,
    'NNE': 1,
    'South': 2,
    'Variable': 5
}